POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkRhdmlkIiwiaWQiOiI2OTdhOWExM2JkMDRkNzJjYTdiZTgyZDgiLCJpYXQiOjE3Njk2NDQwMjl9.qjznFrifw8A8yQ1RfNvLkh9fz7VoxkKRyakOTwSBqzM

{
  "title": "Clean Code: The Good, the Bad and the Ugly",
  "author": "Daniel Gerlach",
  "url": "https://gerlacdt.github.io/blog/posts/clean_code/",
  "likes": 0
}