services:
  app:
    image: hello-front-dev
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
      - /usr/src/app/node_modules # Prevent Windows node_modules from overriding the Linux ones in the container
    ports:
      - 5173:5173
    container_name: hello-front-dev # This will name the container
  # debug-helper:
  #   image: busybox # example on how to use: docker compose -f docker-compose.dev.yml run debug-helper wget -O - http://app:5173
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:  
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app # wait for the frontend container to be started