name: Deployment pipeline

on:
  push:
    branches:
      - main
    paths:
      - '11CI_CD/**'
      - '.github/workflows/**' 
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    paths:
      - '11CI_CD/**'
      - '.github/workflows/**' 

jobs:
  deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version: '20'
      - name: npm install
        working-directory: ./11CI_CD/full-stack-open-pokedex
        run: npm install
      - name: lint
        working-directory: ./11CI_CD/full-stack-open-pokedex
        run: npm run eslint
      - name: test
        working-directory: ./11CI_CD/full-stack-open-pokedex
        run: npm run test
      - name: build
        working-directory: ./11CI_CD/full-stack-open-pokedex
        run: npm run build
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./11CI_CD/full-stack-open-pokedex
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      # - name: deploy on Render
      #   if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
      #   uses: sws2apps/render-deployment@main
      #   with:
      #     serviceId: ${{ secrets.RENDER_SERVICE_ID }}
      #     apiKey: ${{ secrets.RENDER_API_KEY }}
