name: Deployment pipeline

on:
  push:
    branches:
      - main
    paths:
      - '11CI_CD/**'
      - '.github/workflows/**' 
  pull_request:
    branches: [main]
    # Run workflow when PR is opened or when new commits are pushed to the PR
    types: [opened, synchronize]
    paths:
      - '11CI_CD/**'
      - '.github/workflows/**' 

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version: '20'
      - name: npm install
        working-directory: ./11CI_CD/full-stack-open-pokedex
        run: npm install
      - name: lint
        working-directory: ./11CI_CD/full-stack-open-pokedex
        run: npm run eslint
      # - name: test
      #   working-directory: ./11CI_CD/full-stack-open-pokedex
      #   run: npm run test
      - name: build
        working-directory: ./11CI_CD/full-stack-open-pokedex
        run: npm run build
      # - name: e2e tests
      #   uses: cypress-io/github-action@v2
      #   with:
      #     working-directory: ./11CI_CD/full-stack-open-pokedex
      #     command: npm run test:e2e
      #     start: npm run start-prod
      #     wait-on: http://localhost:5000

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
    steps:
      - name: Deploy to Render
        uses: sws2apps/render-deployment@main
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}

  tag_release:
    needs: [build_and_test, deploy]
    runs-on: ubuntu-latest
    #  skips tagging when commit message contains #skip
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '#skip') }} 
    steps:
    - uses: actions/checkout@v4
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.75.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
        MAJOR_STRING_TOKEN: '#major'
        MINOR_STRING_TOKEN: '#minor'
        # NOTE ON HOW TO UPDATE VERSION:
        # git commit -m "fix login crash"           → bumps patch  (1.0.0 → 1.0.1)
        # git commit -m "add user profile page #minor" → bumps minor  (1.0.1 → 1.1.0)
        # git commit -m "redesign API #major"       → bumps major  (1.1.0 → 2.0.0)
        # git commit -m "update readme #skip"       → no tag created at all